### ISSUE TITLE
Consider using a standardized output for verible linter

### ISSUE THREAD

**Issue by tgorochowik** [google/verible#334] opened 2020-06-19 09:17 UTC
It would be beneficial to allow the linter to output it's messages in a way that is standardized and easy to parse by various tool.

@wallento is working on something similar for verilator, it may be a good idea to use exactly the same format in verible to be able to use both linters interchangeably (or together) and not having to worry parsing different outputs.

I think there is no implementation yet, but json and xml are being considered. I'm opening this issue here to track what is happening and discuss ideas.

**Comment by fangism** [comment] 2020-06-19 17:42
Duplicate of #257 .

**Comment by fangism** [comment] 2020-06-19 17:43
Duplicate of #257

**Closed** 2020-06-19 20:04 UTC
Labels: style-linter
